###
GET https://microservicioinenew.onrender.com/api/ine/consulta

###
POST http://127.0.0.1:8000/personas/
Content-Type: application/json

{
  "nombre": "Lucía",
  "apellido_paterno": "Martínez",
  "apellido_materno": "López",
  "fecha_nacimiento": "1985-05-15",
  "sexo": "M",
  "curp": "LUML850515MDFRRC04",
  "direccion": {
    "calle": "Calle del Sol",
    "numero": "456",
    "colonia": "Jardines",
    "municipio": "Guadalajara",
    "estado": "Jalisco",
    "cp": "44100"
  },
  "ine": {
    "clave_elector": "XYZ987654321"
  }
}

###
DELETE http://127.0.0.1:8000/personas/curp/LUML850515MDFRRC04



###
POST http://127.0.0.1:8000/profesionesusuario
Content-Type: application/json

{
  "persona_id": 1,
  "profesion_id": 1
}

###
GET http://127.0.0.1:8000/profesionesusuario

###
GET http://127.0.0.1:8000/profesionesusuario/profesion/1

###
GET http://127.0.0.1:8000/profesionesusuario/detalle
###https://python-eic3.onrender.com/
